### ISSUE TITLE
paging buttons are broken (when going through an alias)

### ISSUE THREAD

**Issue by steveyen** [couchbaselabs/intrapop#16]
it might be because steve increased the results-per-page and perhaps didn't update the paging math

**Comment by steveyen** [comment]
strange: the paging buttons seems to work ok on mac dev box, but not on the intranet VM box.  And, the paging math looks correct.

**Comment by steveyen** [comment]
one difference between the mac dev box and the intranet VM box is the intranet VM box is setup with an extra level of alias, in order to bring in the beer-sample data.  perhaps the paging is getting lost along the way with that extra alias level.

**Comment by steveyen** [comment]
confirmed that the extra alias level has an adverse affect w.r.t. results paging.

**Comment by mschoch** [comment]
I pushed a change which fixes at least one problem.  See https://github.com/blevesearch/bleve/issues/164

However, this issue does not described what "paging buttons are broken" actually means.  Do they not take you anywhere?  Do they show you results from the previous page?  Do they jump around mysteriously?  I don't know, and I couldn't reproduce any unusual behavior in intrapop myself.
