### ISSUE TITLE
support gerrit as a datasource

### ISSUE THREAD

**Issue by mschoch** [couchbaselabs/intrapop#23]
Possibly helpful:

https://github.com/dustin/gerrit-couch/blob/master/tools/watch_gerrit.py

**Comment by steveyen** [comment]
Looks like it's using gerrit's ssh API.  But, it appears most of the interesting entry points are locked down (auth rules denied).

**Comment by steveyen** [comment]
The REST API looks more promising, and some simple curl attempts look like they work...

https://gerrit-review.googlesource.com/Documentation/rest-api.html
